### ISSUE TITLE
Template support formula

### ISSUE THREAD

**Issue by shps951023** [mini-software/MiniExcel#176]
![image](https://user-images.githubusercontent.com/12729184/114682931-250ddd00-9d42-11eb-8ba0-1127a2da824c.png)

**Comment by shps951023** [comment]
Note formula Injection problem

**Comment by shps951023** [comment]
iead:
[Excel模板导出，1.不支持公式？2.不支持合并列？ · Issue #88 · dotnetcore/Magicodes.IE](https://github.com/dotnetcore/Magicodes.IE/issues/88)

**Comment by thirstyape** [comment]
Hello,

To clarify, are formulas in templates supported at all? In my tests I have noticed that if the template contains any formulas the resulting file will be broken. Just basic stuff like `=C9*E9` or `=SUM(F9:F30)`. Even if those columns are left unchanged this will work for what I need, but of course adding more advanced capabilities will be nice also.

This is definitely going to make the library unusable for my purposes if there is no support for formulas. I really like this library and am happy to fork and create something to support that.

Let me know, thanks.

**Comment by jsgervais** [comment]
See pull request #491, I had exactly the same issue, turns out the library needed to reindex the file calcChain.xml in the archive.  It works for single sheet worbooks, for multiple sheets, the library will need to parse worksheet.xml.rels to get corresponding sheets id.
