### ISSUE TITLE
in MiniExcel.SaveAsByTemplate(fileName, @".\Templates\Period_template.xlsx", sheets) double values converted to int

### ISSUE THREAD

**Issue by psxbox** [mini-software/MiniExcel#385]
### Excel Type

- [X] XLSX
- [ ] XLSM
- [ ] CSV
- [ ] OTHER

MiniExcel.SaveAsByTemplate(fileName, @".\Templates\Period_template.xlsx", sheets);
![image](https://user-images.githubusercontent.com/87794982/168424692-efa5f50e-9aa1-44fa-9a2a-c13f8173650c.png)

MiniExcel.SaveAs(fileName, sheets, overwriteFile: true);
![image](https://user-images.githubusercontent.com/87794982/168424759-bcfe2078-804c-4dc0-af7d-3fd453055c4d.png)

### MiniExcel Version
1.26.2

### Description
when calling the MiniExcel.SaveAsByTemplate() double values converted to integer. 
in MiniExcel.SaveAs() is normal

**Comment by shps951023** [comment]
@psxbox 
Could you please provide your country and encoding code?
Thanks

**Comment by psxbox** [comment]
Hi. 
Uzbekistan, 
Code page 1251 | windows-1251 | Cyrillic (Windows)
