### ISSUE TITLE
Are you planning to add a cell formula?

### ISSUE THREAD

**Issue by psxbox** [mini-software/MiniExcel#389]
### Excel Type

- [x] XLSX
- [x] XLSM
- [x] CSV
- [x] OTHER

**Comment by shps951023** [comment]
Yes, MiniExcel has plan to do it, but it needs to change the code style

**Comment by anteeek** [comment]
To anyone who tries hard using formulas like I'm doing right now:
The solution is to use more complex excel formulas (basically just referencing rows in-fly - i.e. 'sum of all rows above me')
For example this formula works: =SUM(INDIRECT(ADDRESS(1,COLUMN())&":"&ADDRESS(ROW()-1,COLUMN())))
(from: https://superuser.com/questions/661847/in-excel-how-can-i-sum-all-the-numbers-above-the-current-cell)
