### ISSUE TITLE
Please strong name sign the assembly

### ISSUE THREAD

**Issue by voltura** [mini-software/MiniExcel#450]
### MiniExcel Version
1.28.1

### Description
![image](https://user-images.githubusercontent.com/2292809/198729992-a13af759-d2f6-473c-98f8-98cf42682814.png)

**Comment by shps951023** [comment]
@voltura v1.28.2 support strong name signature, please feel free to feedback.

**Comment by voltura** [comment]
That was the quickest response and adjustment ever! Thank you!
