### ISSUE TITLE
Problem with multi-line when using Query func

### ISSUE THREAD

**Issue by Sniky83** [mini-software/MiniExcel#507]
### Excel Type

- [x] XLSX
- [x] XLSM
- [X] CSV
- [x] OTHER

### Upload Excel File
e.g : [.NET Fiddle](https://dotnetfiddle.net/jBO3C6)

### MiniExcel Version
1.31

### Description
I wanted to import a CSV file in my project by reading the infos of the file and I jumped lines in my cells and I've seen that I would have more lines found than expected.

So when you put in a cell a retrun line you have a trouble, your code create a new object instead of adding the cell with the x jumping lines in the current object.

Check the .NET fiddle link and run it to understand easily what i'm meaning.

**Comment by shps951023** [comment]
![image](https://github.com/mini-software/MiniExcel/assets/12729184/1325f9ea-b1c5-4d2d-8b1f-3b716dd16b7c)

**Comment by Sniky83** [comment]
The problem is when I want to use the Query Method from your lib, it's not working, "Microsoft Test" doesn't go in the same object but it is split in two differents object which is wrong.
