### ISSUE TITLE
使用EXCEL 模板导出 样式发现变化

### ISSUE THREAD

**Issue by FPHFZM** [mini-software/MiniExcel#508]
![LF(F(3Z%@MLE26}JTK3RLA](https://github.com/mini-software/MiniExcel/assets/45850788/ffaa75a6-c56f-400a-af89-eefc2fc0a4be)
上面是我的模板  

导出后 样式发生了变化
![NUGPG`B`BG LVT}LN8)~AYQ](https://github.com/mini-software/MiniExcel/assets/45850788/8371e5fa-d60e-4d6b-81c0-94415e1ee5da)
麻烦大佬百忙之中看一下

**Comment by shps951023** [comment]
需要文件测试 @FPHFZM

**Comment by FPHFZM** [comment]
已解决
