### ISSUE TITLE
CSV created a data error “Type <>f__AnonymousType0`3 & genericType  not Implemented. please issue for me.”

### ISSUE THREAD

**Issue by xiaoxinpro** [mini-software/MiniExcel#534]
### Excel Type

- [ ] XLSX
- [ ] XLSM
- [x] CSV
- [ ] OTHER

### Upload Excel File
CSV creation failed, no file

### MiniExcel Version
V1.31.2

### Description

Reproducing code:
```
{
    string path = Path.Combine(AppDomain.CurrentDomain.SetupInformation.ApplicationBase, "test.csv");
    var value = new { ID = 1, Name = "Jack", InDate = new DateTime(2021, 01, 03) };
    MiniExcel.SaveAs(path, value);
}
```

Exception message：
```
System.NotImplementedException:“Type <>f__AnonymousType0`3 & genericType  not Implemented. please issue for me.”
```

**Comment by pszybiak** [comment]
If you whant to create new CSV file you should specify value argument as table:

```
{
    string path = Path.Combine(AppDomain.CurrentDomain.SetupInformation.ApplicationBase, "test.csv");
    var value = new[] {
          new { ID=1,Name ="Jack",InDate=new DateTime(2021,01,03)}
    };
    MiniExcel.SaveAs(path, value, excelType: ExcelType.CSV);
}
```
If you want add one record to existing file you need use `Insert` method:

```
{ 
    var value = new { ID=1,Name = "Jack", InDate = new DateTime(2021,01,03) };
    MiniExcel.Insert(path, value);
}
```

**Comment by xiaoxinpro** [comment]
> If you whant to create new CSV file you should specify value argument as table:
> 
> ```
> {
>     string path = Path.Combine(AppDomain.CurrentDomain.SetupInformation.ApplicationBase, "test.csv");
>     var value = new[] {
>           new { ID=1,Name ="Jack",InDate=new DateTime(2021,01,03)}
>     };
>     MiniExcel.SaveAs(path, value, excelType: ExcelType.CSV);
> }
> ```
> 
> If you want add one record to existing file you need use `Insert` method:
> 
> ```
> { 
>     var value = new { ID=1,Name = "Jack", InDate = new DateTime(2021,01,03) };
>     MiniExcel.Insert(path, value);
> }
> ```

This method works.
