### ISSUE TITLE
Dapper Query 支持延迟加载，README.zh-CN.md 文件中的说法错误

### ISSUE THREAD

**Issue by shaofing** [mini-software/MiniExcel#552]
README.zh-CN.md 文件中的说法错误
https://github.com/mini-software/MiniExcel/blob/master/README.zh-CN.md#5-dapper-query

` var details = conn.Query<receipt_detail>(new CommandDefinition(sql, CommandFlags.NoCache)); //必须使用NoCache`

使用`new CommandDefinition(sql, CommandFlags.NoCache)` 可以支持延迟加载

**Comment by shps951023** [comment]
@shaofing 谢谢👍
已更正说法

**Comment by shaofing** [comment]
1 ，上面的demo写法不对 ， flags 前面还有可选参数，如果不按照顺序写 ，参数得是 `new CommandDefinition(sql, flags: CommandFlags.NoCache)`
2，不能ToList() 。
3，使用CommandFlags.NoCache时，不能使用异步QueryAsync的方法，会报连接已经关闭的异常
`
            var details = conn.Query<receipt_detail>(new CommandDefinition(sql, flags: CommandFlags.NoCache));
            MiniExcel.SaveAs(fileName, details);
`

**Comment by shps951023** [comment]
@shaofing 请问能帮忙PR吗?

**Comment by shaofing** [comment]
https://github.com/mini-software/MiniExcel/pull/554
