### ISSUE TITLE
Cell formatted as "Custom" ("h:mm") with value "13:00" is shown deserialized in the C# code as "12:59:59.9999"

### ISSUE THREAD

**Issue by ZackStone** [mini-software/MiniExcel#570]
### Excel Type

- [X] XLSX
- [ ] XLSM
- [ ] CSV
- [ ] OTHER

### Upload Excel File
[issue.xlsx](https://github.com/mini-software/MiniExcel/files/14552008/issue.xlsx)

### MiniExcel Version
1.31.3

### Description
Cell formatted as "Custom" ("h:mm") with value "13:00" is shown deserialized in the C# code as "12:59:59.9999".

![image](https://github.com/mini-software/MiniExcel/assets/9125490/2a643a5d-acaf-4f50-beef-61e64c8ff4f9)

![image](https://github.com/mini-software/MiniExcel/assets/9125490/c9a3b183-d880-4e65-99e0-cc9d0c208161)

### Repro

https://github.com/ZackStone/MiniExcelIssue

**Comment by jiaguangli** [comment]
hi，
thank for your issure,
Custome types will be converted to numberic values by excel 
Please use "Time" Type 
![image](https://github.com/mini-software/MiniExcel/assets/35099424/852b0db8-1660-4954-a42e-4f01cb85f735)

console
![image](https://github.com/mini-software/MiniExcel/assets/35099424/391d1d45-8029-4294-8bf5-2980608c7e47)

**Comment by jiaguangli** [comment]
Did it solve your problem?
