### ISSUE TITLE
dependency bug with `Portable.System.DateTimeOnly`

### ISSUE THREAD

**Issue by MarcelWilke42** [mini-software/MiniExcel#594]
### MiniExcel Version
[1.32.0](https://github.com/mini-software/MiniExcel/releases/tag/1.32.0)
### Description

Since #576 there is a dependency bug.

[Here](https://github.com/mini-software/MiniExcel/blob/master/src/MiniExcel/MiniExcelLibs.csproj#L57) it is explicitly checked that this is only included with `netstandard2.0`. But since `MiniExcel` is only built for `net45` and `netstandard2.0` this means that e.g. a `net8` project that includes `MiniExcel` (in this case the `netstandard2.0` lib) automatically includes `Portable.System.DateTimeOnly`.

This could only be prevented cleanly by building `MiniExcel` in different frameworks.

**Comment by shps951023** [comment]
@MarcelWilke42 Fixed v1.32.1
