### ISSUE TITLE
SaveAsByTemplate uses too much memory

### ISSUE THREAD

**Issue by Kikitka** [mini-software/MiniExcel#606]
### Excel Type

- [x] XLSX
- [ ] XLSM
- [ ] CSV
- [ ] OTHER

### MiniExcel Version
1.32.1

### Template excel file
[Template.xlsx](https://github.com/mini-software/MiniExcel/files/15415088/Template.xlsx)

### Description
![image](https://github.com/mini-software/MiniExcel/assets/63345800/7388a826-cfa0-4936-bbf1-ee33070da023)
Maybe, I using it incorrectly. I will be glad to receive an answer.....

**Comment by meld-cp** [comment]
This should be fixed in v1.34.0
