### ISSUE TITLE
MiniExcel.Insert()方法无法正常追加CSV文件

### ISSUE THREAD

**Issue by C-Li** [mini-software/MiniExcel#643]
### Excel Type

- [ ] XLSX
- [ ] XLSM
- [x] CSV
- [ ] OTHER

### Upload Excel File

Please attach your issue file by dragging or droppng, selecting or pasting them.

[test.csv](https://github.com/user-attachments/files/16411827/test.csv)

### MiniExcel Version
1.34.0.0

### Description
照示例写了CSV追加的程序，但似乎只能从第一行开始追加，会覆盖原有的数据。
![image](https://github.com/user-attachments/assets/4cce2fc6-bc73-4058-b2a2-db0655525f7a)

```
string filePath = Path.Combine(CommonHelper.GetBaseDataDirectory(), "test.csv");
var objList = new[] {
                      new { ID=1,Name ="Frank",InDate=new DateTime(2021,06,07)},
                      new { ID=2,Name ="Gloria",InDate=new DateTime(2022,05,03)},
                };
using (var stream = File.OpenWrite(filePath))
{
    MiniExcel.SaveAs(stream, objList, true, "data", ExcelType.CSV);
}
objList = new[] {
                  new { ID=3,Name ="Frank",InDate=new DateTime(2021,06,07)},
                  new { ID=4,Name ="Gloria",InDate=new DateTime(2022,05,03)},
            };
using (var stream = File.OpenWrite(filePath))
{
    MiniExcel.Insert(stream, objList, "data", ExcelType.CSV);
}
```
执行的结果：
![image](https://github.com/user-attachments/assets/f8f75df2-edb2-40e0-ab63-d9afb404b345)

而且这里的 Insert 必须指明是 ExcelType.CSV ,不然会报错: System.NotImplementedException:“未实现该方法或操作。”

**Comment by izanhzh** [comment]
在insert前加语句将流的当前位置设置到流的末尾：
```csharp
stream.Seek(0, SeekOrigin.End);
```
获取不要用File.OpenWrite，改为：
```csharp
var stream = new FileStream(path, FileMode.Append, FileAccess.Write, FileShare.Read, 4096, FileOptions.SequentialScan)
```

或者等作者大佬微调下了
