### ISSUE TITLE
Auto adjust column width for excel writing

### ISSUE THREAD

**Issue by Discolai** [mini-software/MiniExcel#682]
### Excel Type

- [x] XLSX
- [x] XLSM
- [ ] CSV
- [ ] OTHER

I have been looking into implementing an autosize feature in a similar fashion as dimensions are handled in fastmode.

Fastmode changes the filemode of the zipfile to support seeking. Is there a reason why this is not the default? Is it slower?

The autosize feature would require fastmode to be enabled. So I want to remove the fastmode option and make it the default behaviour if you have no objections @shps951023

**Comment by oukene** [comment]
I have a question,
How did you use autofit by adjusting fastmode?

Can you show me an example?

**Comment by Discolai** [comment]
It is not just adjusting FastMode, but some internal changes to how things are written.

My branch is still a work in process, but I will publish a pr when I think it is ready
